[project]
name = "bflookup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
    "pyyaml>=6.0.2",
    "ruff>=0.9.9",
]

[tool.ruff]
select = ["E", "F", "I"]
